In [5]:
import numpy as np

In [12]:


#Pair Numpy
# Creación y Indexación:
# 1- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

mult = np.random.randint(10, 99, 50)
print(mult)
mult [4::5]





[56 22 81 56 37 52 82 15 81 29 30 68 84 51 27 84 94 85 48 62 61 87 92 67
 45 80 73 44 24 62 46 12 49 47 86 51 57 74 33 33 94 81 32 27 95 95 45 63
 55 31]


array([37, 29, 27, 62, 45, 62, 86, 33, 95, 31])

In [31]:

#2-Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). 
# Utiliza indexación para obtener los elementos en las posiciones impares.

mult1 = np.random.randint(0, 21, 30)
print(mult1)
mult1[::2]



[ 7  3  2 11  2 11  5  1  0  4  6 15 11 14 20 15 15  2  4  0  8  5  0  4
  9 15 12 10  1 17]


array([ 7,  2,  2,  5,  0,  6, 11, 20, 15,  4,  8,  0,  9, 12,  1])

In [32]:
#3- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1).
#  Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

decim = np.random.rand(4,6)
print(decim)
decim[3]
decim[3].round(2)

[[0.51861647 0.58921663 0.29931011 0.44002187 0.21859905 0.6787488 ]
 [0.82452648 0.90238876 0.99810899 0.83974473 0.52449143 0.69749226]
 [0.15311988 0.1168334  0.05835078 0.93204969 0.57031968 0.11802038]
 [0.671459   0.51847816 0.06173118 0.68580276 0.48721305 0.13376774]]


array([0.67, 0.52, 0.06, 0.69, 0.49, 0.13])

In [38]:
#4- BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos).
#  Reemplaza los elementos en posiciones múltiplos de 3 por 0.
mult1 = np.random.randint(0, 101,(2,3,5))
print(mult1)
mult1[:,::3,:]
reemplazar= mult1[::3] = 0
print(reemplazar)

[[[53 85 89 21 56]
  [56 34  5 34 48]
  [83 32 74 14 27]]

 [[47 63 52 57 51]
  [71 89 76 98 42]
  [99 24 74 74 57]]]
0


In [ ]:
# Reshape y Transpose:
# Ejercicios con reshape:
# Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive).
#  Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

# Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). 
# Utiliza reshape para convertirlo en un array 2D.

In [ ]:
# Ejercicios con transpose:
# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y 
# obtener un nuevo array con forma (3, 5, 4).

In [ ]:
# Preguntas teóricas:
# ¿Qué diferencia existe entre el reshape y el transpose?

# ¿Y entre el transpose y el swapaxes?

In [ ]:
# Funciones Aritméticas y Estadísticas:
# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

# Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos 
# en los valores del primer array bajo las siguientes condiciones:

# Si el valor del array es igual que la media, se reemplaza por "A".

# Si el valor del array es mayor que la media, se reemplaza por "B".

# Si el valor del array es menor que la media, se reemplaza por "C".

# Si el valor es igual que el máximo, se reemplaza por "D".

# Si el valor es igual que el mínimo, se reemplaza por "E".

# Copy
# # a modo de ejemplo. Si tenemos el siguiente array
# [[[0.4, 0.7, 0.2, 0.9, 0.2],
#     [0.1, 0.9, 0.6, 0.1, 0.2],
#     [1. , 0.2, 0.1, 0.8, 0.3]],

# [[0. , 0.3, 0.4, 0.5, 0.1],
#     [0.5, 0.7, 0.9, 0. , 0.8],
#     [0.5, 0.3, 0.5, 0.8, 0.1]]])

# # sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# # nuestro array vacío debería quedar como este: 
# [[["A", "B", "C", "B", "C"],
#     ["C", "B", "B", "C", "C"],
#     ["D" , "C", "C", "B", "C"]],

# [["E" , "C", "A", "B", "C"],
#     ["B", "B","B", "E" , "B"],
#     ["B", "C", "B", "B", "C"]]])