In [2]:
import numpy as np

In [3]:


#Pair Numpy
# Creación y Indexación:
# 1- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

mult = np.random.randint(10, 99, 50)
print(mult)
mult [4::5]





[44 50 63 32 69 36 29 38 78 47 81 55 37 75 48 63 48 88 70 16 23 76 54 55
 53 50 36 53 42 47 67 49 97 38 42 48 14 72 45 86 10 40 25 39 88 29 57 75
 78 78]


array([69, 47, 48, 16, 53, 47, 42, 86, 88, 78])

In [4]:

#2-Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). 
# Utiliza indexación para obtener los elementos en las posiciones impares.

mult1 = np.random.randint(0, 21, 30)
print(mult1)
mult1[::2]



[ 0 12  1  1  9 12  7 15  1 12 14 13 14  1  3 16 14 17 16 19 19  0  1  9
  5 17 20 10 10 14]


array([ 0,  1,  9,  7,  1, 14, 14,  3, 14, 16, 19,  1,  5, 20, 10])

In [5]:
#3- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1).
#  Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

decim = np.random.rand(4,6)
print(decim)
decim[3]
decim[3].round(2)

[[0.72649751 0.46760738 0.70738869 0.45987736 0.54438561 0.85223479]
 [0.22668952 0.22859607 0.85539763 0.45327295 0.34631263 0.64346601]
 [0.09493933 0.35954098 0.81747994 0.36012158 0.42671748 0.89489192]
 [0.48607269 0.90628097 0.61977982 0.75261897 0.15789426 0.12886392]]


array([0.49, 0.91, 0.62, 0.75, 0.16, 0.13])

In [50]:
#4- BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos).
#  Reemplaza los elementos en posiciones múltiplos de 3 por 0.
mult1 = np.random.randint(0, 101,(2,3,5))
print(mult1)


for i in range(0,2):
    for e in range(0,3):
        mult1[i,e,2] = 0
           
        
mult1


[[[31 76 67 46 14]
  [ 7 49  0 30 35]
  [60 86 33  9 93]]

 [[41 76 66 55 18]
  [95 62 15 17 40]
  [99 71 16 44 40]]]


array([[[31, 76,  0, 46, 14],
        [ 7, 49,  0, 30, 35],
        [60, 86,  0,  9, 93]],

       [[41, 76,  0, 55, 18],
        [95, 62,  0, 17, 40],
        [99, 71,  0, 44, 40]]])

In [ ]:
# Reshape y Transpose:
# Ejercicios con reshape:
# Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive).
#  Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

# Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). 
# Utiliza reshape para convertirlo en un array 2D.

In [51]:

# Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive).
mresha = np.random.randint(0, 101,(2,3,4))
print(mresha)

mresha2 = mresha.reshape(2,12)
print(mresha2)


# Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.
mresha3 = np.random.randint(1, 61,(3,4,5))
mresha32d = mresha3.reshape(2,30)





[[[42 87 20 16]
  [88 35 56 53]
  [32  2  1 27]]

 [[90 85 64 98]
  [75 84 35 74]
  [70 12  2 75]]]
[[42 87 20 16 88 35 56 53 32  2  1 27]
 [90 85 64 98 75 84 35 74 70 12  2 75]]


In [66]:
# Ejercicios con transpose:
# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
mresha3 = np.random.randint(1, 61,(3,4,5))
trans = np.transpose(mresha3, (2, 1, 0))
trans

# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y 
# obtener un nuevo array con forma (3, 5, 4).
mresha3 = np.random.randint(1, 61,(3,4,5))
trans2 = np.transpose(mresha3, (0,2,1))
trans2


array([[[27, 40,  6, 48],
        [56, 42, 44, 30],
        [34, 32, 28,  7],
        [26, 25, 52, 18],
        [40,  9, 34, 14]],

       [[39, 45,  9, 15],
        [47, 38, 18, 32],
        [ 4,  5,  6, 45],
        [23, 34, 49, 45],
        [11, 11, 55, 53]],

       [[44, 40, 28, 38],
        [ 5, 19, 31, 57],
        [30, 29, 35, 45],
        [18, 33, 31, 58],
        [42, 60, 54, 54]]])

In [ ]:
# Preguntas teóricas:
# ¿Qué diferencia existe entre el reshape y el transpose?

# ¿Y entre el transpose y el swapaxes?

In [75]:
# Funciones Aritméticas y Estadísticas:
# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.
array3d = np.random.rand(2,3,5)
r= array3d.round(1)
r



# Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 

array3d2 = np.random.rand(2,3,5)

# Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos 
# en los valores del primer array bajo las siguientes condiciones:

# Si el valor del array es igual que la media, se reemplaza por "A".

# Si el valor del array es mayor que la media, se reemplaza por "B".

# Si el valor del array es menor que la media, se reemplaza por "C".

# Si el valor es igual que el máximo, se reemplaza por "D".

# Si el valor es igual que el mínimo, se reemplaza por "E".

# Copy
# # a modo de ejemplo. Si tenemos el siguiente array
# [[[0.4, 0.7, 0.2, 0.9, 0.2],
#     [0.1, 0.9, 0.6, 0.1, 0.2],
#     [1. , 0.2, 0.1, 0.8, 0.3]],

# [[0. , 0.3, 0.4, 0.5, 0.1],
#     [0.5, 0.7, 0.9, 0. , 0.8],
#     [0.5, 0.3, 0.5, 0.8, 0.1]]])

# # sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# # nuestro array vacío debería quedar como este: 
# [[["A", "B", "C", "B", "C"],
#     ["C", "B", "B", "C", "C"],
#     ["D" , "C", "C", "B", "C"]],

# [["E" , "C", "A", "B", "C"],
#     ["B", "B","B", "E" , "B"],
#     ["B", "C", "B", "B", "C"]]])

array([[[0.2, 0.1, 0.1, 0.9, 0.3],
        [0.2, 0.9, 0.3, 0.5, 0.7],
        [0.6, 0.3, 0.9, 1. , 0.1]],

       [[1. , 0.7, 0.5, 0.7, 0.2],
        [0. , 0.3, 0.3, 0.3, 0. ],
        [0.2, 0.4, 0.2, 0.8, 0.4]]])